name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

env:
  DOTNET_VERSION: 8.0.x

jobs:
  build:
    permissions:
      contents: read
      actions: read
      checks: write

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      run: dotnet build -c Release

    - name: Run Tests
      run: dotnet test -c Release --no-build --logger "trx;LogFileName=results.trx"

    - name: Test Reporter
      uses: dorny/test-reporter@v1.7.0
      if: success() || failure()
      with:
        name: NUnit Tests (${{ matrix.os }})
        path: tests/AdventOfCode.Test/TestResults/results.trx
        reporter: dotnet-trx

  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      run: dotnet build -c Release

    - name: Run
      run: dotnet run -c Release --no-build -- all
      working-directory: ./src/AdventOfCode
