name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

env:
  DOTNET_VERSION: 8.0.x
  AOC_CLI_VERSION: 0.12.0

jobs:
  test:
    permissions:
      contents: read
      actions: read
      checks: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install aoc-cli
      run: |
        wget -nv https://github.com/scarvalhojr/aoc-cli/releases/download/${{ env.AOC_CLI_VERSION}}/aoc-cli-${{ env.AOC_CLI_VERSION}}-x86_64-unknown-linux-musl.tar.gz
        tar -xzvf aoc-cli-${{ env.AOC_CLI_VERSION}}-x86_64-unknown-linux-musl.tar.gz
        echo "${PWD}/aoc-cli-${{ env.AOC_CLI_VERSION}}-x86_64-unknown-linux-musl/" >> $GITHUB_PATH

    - name: Download puzzle input
      run: |
        mkdir -p src/AdventOfCode/Inputs
        for i in $(seq -w 25);do
            aoc download -y 2023 -d $i -I -i src/AdventOfCode/Inputs/$i.txt
        done
      env:
        ADVENT_OF_CODE_SESSION: ${{ secrets.ADVENT_OF_CODE_SESSION }}
      continue-on-error: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      run: dotnet build -c Release

    - name: Run Tests
      run: dotnet test -c Release --no-build --logger "trx;LogFileName=results.trx"

    - name: Test Reporter
      uses: dorny/test-reporter@v1.7.0
      if: success() || failure()
      with:
        name: NUnit Tests
        path: tests/AdventOfCode.Test/TestResults/results.trx
        reporter: dotnet-trx

  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install aoc-cli
      run: |
        wget -nv https://github.com/scarvalhojr/aoc-cli/releases/download/${{ env.AOC_CLI_VERSION}}/aoc-cli-${{ env.AOC_CLI_VERSION}}-x86_64-unknown-linux-musl.tar.gz
        tar -xzvf aoc-cli-${{ env.AOC_CLI_VERSION}}-x86_64-unknown-linux-musl.tar.gz
        echo "${PWD}/aoc-cli-${{ env.AOC_CLI_VERSION}}-x86_64-unknown-linux-musl/" >> $GITHUB_PATH

    - name: Download puzzle input
      run: |
        mkdir -p src/AdventOfCode/Inputs
        for i in $(seq -w 25);do
            aoc download -y 2023 -d $i -I -i src/AdventOfCode/Inputs/$i.txt
        done
      env:
        ADVENT_OF_CODE_SESSION: ${{ secrets.ADVENT_OF_CODE_SESSION }}
      continue-on-error: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      run: dotnet build -c Release

    - name: Run
      run: dotnet run -c Release --no-build -- all
      working-directory: ./src/AdventOfCode
